"""add void fields to ar ap payments

Revision ID: 2094746b9c0a
Revises: faf29a3a5aec
Create Date: 2026-05-15 16:37:49.508471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2094746b9c0a'
down_revision: Union[str, None] = 'faf29a3a5aec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ap_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('voided_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('void_reason', sa.String(length=500), nullable=True))
        batch_op.create_foreign_key(
            'fk_ap_payments_voided_by_id_users', 'users', ['voided_by_id'], ['id'],
            ondelete='RESTRICT',
        )

    with op.batch_alter_table('ar_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('voided_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('void_reason', sa.String(length=500), nullable=True))
        batch_op.create_foreign_key(
            'fk_ar_payments_voided_by_id_users', 'users', ['voided_by_id'], ['id'],
            ondelete='RESTRICT',
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ar_payments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ar_payments_voided_by_id_users', type_='foreignkey')
        batch_op.drop_column('void_reason')
        batch_op.drop_column('voided_by_id')
        batch_op.drop_column('voided_at')

    with op.batch_alter_table('ap_payments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ap_payments_voided_by_id_users', type_='foreignkey')
        batch_op.drop_column('void_reason')
        batch_op.drop_column('voided_by_id')
        batch_op.drop_column('voided_at')

    # ### end Alembic commands ###
