"""add ar ap tables payment terms tax mode

Revision ID: 2a90b8578951
Revises: 44e0c29ad088
Create Date: 2026-05-15 13:20:33.632061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a90b8578951'
down_revision: Union[str, None] = '44e0c29ad088'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts_payable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ap_number', sa.String(length=32), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('amount_untaxed', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('amount_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.Enum('open', 'partial', 'paid', 'voided', name='payable_status'), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounts_payable', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_payable_ap_number'), ['ap_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_accounts_payable_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_payable_issued_at'), ['issued_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_payable_purchase_order_id'), ['purchase_order_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_accounts_payable_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_payable_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('accounts_receivable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ar_number', sa.String(length=32), nullable=False),
    sa.Column('sales_order_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('amount_untaxed', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('amount_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.Enum('open', 'partial', 'paid', 'voided', name='receivable_status'), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounts_receivable', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_receivable_ar_number'), ['ar_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_accounts_receivable_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_receivable_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_receivable_issued_at'), ['issued_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_receivable_sales_order_id'), ['sales_order_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_accounts_receivable_status'), ['status'], unique=False)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'payment_terms_days',
                sa.Integer(),
                nullable=False,
                server_default=sa.text('30'),
            )
        )

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'is_tax_inclusive',
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )

    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'is_tax_inclusive',
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'payment_terms_days',
                sa.Integer(),
                nullable=False,
                server_default=sa.text('30'),
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_column('payment_terms_days')

    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.drop_column('is_tax_inclusive')

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_column('is_tax_inclusive')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('payment_terms_days')

    with op.batch_alter_table('accounts_receivable', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_receivable_status'))
        batch_op.drop_index(batch_op.f('ix_accounts_receivable_sales_order_id'))
        batch_op.drop_index(batch_op.f('ix_accounts_receivable_issued_at'))
        batch_op.drop_index(batch_op.f('ix_accounts_receivable_due_date'))
        batch_op.drop_index(batch_op.f('ix_accounts_receivable_customer_id'))
        batch_op.drop_index(batch_op.f('ix_accounts_receivable_ar_number'))

    op.drop_table('accounts_receivable')
    with op.batch_alter_table('accounts_payable', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_payable_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_accounts_payable_status'))
        batch_op.drop_index(batch_op.f('ix_accounts_payable_purchase_order_id'))
        batch_op.drop_index(batch_op.f('ix_accounts_payable_issued_at'))
        batch_op.drop_index(batch_op.f('ix_accounts_payable_due_date'))
        batch_op.drop_index(batch_op.f('ix_accounts_payable_ap_number'))

    op.drop_table('accounts_payable')
    # ### end Alembic commands ###
