"""add low_stock_threshold to products

Revision ID: 7af62035ac02
Revises: 9f4ea2667fc9
Create Date: 2026-05-13 21:49:15.418564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7af62035ac02'
down_revision: Union[str, None] = '9f4ea2667fc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'low_stock_threshold',
                sa.Integer(),
                nullable=False,
                server_default='0',
            )
        )
    # Strip the server_default so future inserts go through the ORM default instead.
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('low_stock_threshold', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('low_stock_threshold')

    # ### end Alembic commands ###
