"""add employees and salary records

Revision ID: a601cdb06d7c
Revises: d8a3c7e2f456
Create Date: 2026-05-21 14:10:31.066513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a601cdb06d7c'
down_revision: Union[str, None] = 'd8a3c7e2f456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('employee_number', sa.String(length=32), nullable=False),
    sa.Column('department', sa.Enum('sales', 'warehouse', 'accounting', 'management', 'it', name='employee_department'), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('employment_type', sa.Enum('full_time', 'part_time', 'contractor', name='employee_employment_type'), nullable=False),
    sa.Column('base_salary', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_department'), ['department'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_employee_number'), ['employee_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_employees_user_id'), ['user_id'], unique=True)

    op.create_table('salary_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reason', sa.Enum('hire', 'promotion', 'adjustment', 'correction', name='salary_change_reason'), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_salary_records_amount_non_negative'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('salary_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_salary_records_effective_date'), ['effective_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_salary_records_employee_id'), ['employee_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salary_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_salary_records_employee_id'))
        batch_op.drop_index(batch_op.f('ix_salary_records_effective_date'))

    op.drop_table('salary_records')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_user_id'))
        batch_op.drop_index(batch_op.f('ix_employees_employee_number'))
        batch_op.drop_index(batch_op.f('ix_employees_department'))

    op.drop_table('employees')
    # ### end Alembic commands ###
