"""add ar ap payments

Revision ID: ef4e31e22bba
Revises: 2a90b8578951
Create Date: 2026-05-15 14:41:17.057791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef4e31e22bba'
down_revision: Union[str, None] = '2a90b8578951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ap_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_number', sa.String(length=32), nullable=False),
    sa.Column('accounts_payable_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('method', sa.Enum('cash', 'bank_transfer', 'check', 'other', name='payment_method'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reference', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_ap_payments_amount_positive'),
    sa.ForeignKeyConstraint(['accounts_payable_id'], ['accounts_payable.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ap_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ap_payments_accounts_payable_id'), ['accounts_payable_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ap_payments_operator_id'), ['operator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ap_payments_paid_at'), ['paid_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ap_payments_payment_number'), ['payment_number'], unique=True)

    op.create_table('ar_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_number', sa.String(length=32), nullable=False),
    sa.Column('accounts_receivable_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('method', sa.Enum('cash', 'bank_transfer', 'check', 'other', name='payment_method'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reference', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_ar_payments_amount_positive'),
    sa.ForeignKeyConstraint(['accounts_receivable_id'], ['accounts_receivable.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ar_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ar_payments_accounts_receivable_id'), ['accounts_receivable_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ar_payments_operator_id'), ['operator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ar_payments_paid_at'), ['paid_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ar_payments_payment_number'), ['payment_number'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ar_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ar_payments_payment_number'))
        batch_op.drop_index(batch_op.f('ix_ar_payments_paid_at'))
        batch_op.drop_index(batch_op.f('ix_ar_payments_operator_id'))
        batch_op.drop_index(batch_op.f('ix_ar_payments_accounts_receivable_id'))

    op.drop_table('ar_payments')
    with op.batch_alter_table('ap_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ap_payments_payment_number'))
        batch_op.drop_index(batch_op.f('ix_ap_payments_paid_at'))
        batch_op.drop_index(batch_op.f('ix_ap_payments_operator_id'))
        batch_op.drop_index(batch_op.f('ix_ap_payments_accounts_payable_id'))

    op.drop_table('ap_payments')
    # ### end Alembic commands ###
